all : main1.exe main2.exe main3.exe

main1.exe : main1.cpp
	g++ main1.cpp -o main1.exe

main2.exe : main2.cpp
	g++ main2.cpp -o main2.exe

main3.exe : main3.cpp
	g++ main3.cpp -o main3.exe

clean : 
	rm *.exe

.PHONY: all clean